#!/bin/bash

# 🚀 GUÍA RÁPIDA DE DEPLOYMENT
# Ejecuta estos comandos paso a paso para configurar el deployment automático

echo "======================================================================"
echo "  CONFIGURACIÓN DE CI/CD - Microservicio de Productos"
echo "  EC2: 54.158.158.91 | Puerto: 8081 | GitHub: producto-huerto"
echo "======================================================================"
echo ""

# ============================================
# PASO 1: CONFIGURAR EC2 (Primera vez)
# ============================================
echo "PASO 1: CONFIGURAR EC2"
echo "======================================================================"
echo ""
echo "1.1 Copiar archivos a EC2:"
echo ""
echo "scp -i TU_CLAVE.pem setup-ec2.sh ubuntu@54.158.158.91:/home/ubuntu/"
echo "scp -i TU_CLAVE.pem producto-service.service ubuntu@54.158.158.91:/home/ubuntu/"
echo "scp -i TU_CLAVE.pem check-service.sh ubuntu@54.158.158.91:/home/ubuntu/"
echo ""
echo "1.2 Conectarse a EC2 y ejecutar setup:"
echo ""
echo "ssh -i TU_CLAVE.pem ubuntu@54.158.158.91"
echo "chmod +x setup-ec2.sh check-service.sh"
echo "./setup-ec2.sh"
echo "exit"
echo ""
read -p "Presiona ENTER cuando hayas completado el Paso 1..."
echo ""

# ============================================
# PASO 2: CONFIGURAR SECRETS EN GITHUB
# ============================================
echo "PASO 2: CONFIGURAR SECRETS EN GITHUB"
echo "======================================================================"
echo ""
echo "2.1 Abre en tu navegador:"
echo ""
echo "https://github.com/ctapiad/producto-huerto/settings/secrets/actions"
echo ""
echo "2.2 Crea estos 3 secrets:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Secret 1: EC2_HOST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Valor: 54.158.158.91"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Secret 2: EC2_USER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Valor: ubuntu"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Secret 3: EC2_SSH_KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Valor: Contenido completo de tu archivo .pem"
echo ""
echo "Para obtener el contenido de tu clave .pem:"
echo "cat TU_CLAVE.pem"
echo ""
echo "Copia TODO incluyendo:"
echo "-----BEGIN RSA PRIVATE KEY-----"
echo "... (contenido)"
echo "-----END RSA PRIVATE KEY-----"
echo ""
read -p "Presiona ENTER cuando hayas configurado los 3 secrets..."
echo ""

# ============================================
# PASO 3: ACTIVAR PRIMER DEPLOYMENT
# ============================================
echo "PASO 3: ACTIVAR PRIMER DEPLOYMENT"
echo "======================================================================"
echo ""
echo "El código ya está en GitHub. Para activar el deployment:"
echo ""
echo "Opción A - Trigger vacío:"
echo "git commit --allow-empty -m 'Activar primer deployment'"
echo "git push origin main"
echo ""
echo "Opción B - Con cambio real:"
echo "# Haz cualquier cambio en el código"
echo "git add ."
echo "git commit -m 'Trigger deployment'"
echo "git push origin main"
echo ""
read -p "Presiona ENTER cuando hayas hecho push a GitHub..."
echo ""

# ============================================
# PASO 4: MONITOREAR DEPLOYMENT
# ============================================
echo "PASO 4: MONITOREAR DEPLOYMENT"
echo "======================================================================"
echo ""
echo "4.1 Abre en tu navegador:"
echo ""
echo "https://github.com/ctapiad/producto-huerto/actions"
echo ""
echo "4.2 Verás el workflow 'CI/CD Pipeline - Deploy to AWS EC2' ejecutándose"
echo ""
echo "4.3 Espera ~3-5 minutos hasta que complete"
echo ""
echo "4.4 Verifica que todos los pasos estén en verde (✓)"
echo ""
read -p "Presiona ENTER cuando el deployment haya completado..."
echo ""

# ============================================
# PASO 5: VERIFICAR SERVICIO
# ============================================
echo "PASO 5: VERIFICAR SERVICIO"
echo "======================================================================"
echo ""
echo "5.1 Test desde tu máquina local:"
echo ""
echo "curl http://54.158.158.91:8081/api/productos/health"
echo ""
echo "Deberías recibir:"
echo "Servicio de productos funcionando correctamente en puerto 8081"
echo ""
echo ""
echo "5.2 Verificar en EC2:"
echo ""
echo "ssh -i TU_CLAVE.pem ubuntu@54.158.158.91"
echo "./check-service.sh"
echo ""
echo ""
echo "5.3 Swagger UI:"
echo ""
echo "http://54.158.158.91:8081/swagger-ui/index.html"
echo ""
echo ""
echo "5.4 Probar endpoints:"
echo ""
echo "curl http://54.158.158.91:8081/api/productos"
echo "curl http://54.158.158.91:8081/api/productos/FR001"
echo "curl 'http://54.158.158.91:8081/api/productos/buscar?nombre=manzana'"
echo ""

# ============================================
# RESUMEN FINAL
# ============================================
echo ""
echo "======================================================================"
echo "  ✅ CONFIGURACIÓN COMPLETA"
echo "======================================================================"
echo ""
echo "URLs del servicio:"
echo "  • Health:   http://54.158.158.91:8081/api/productos/health"
echo "  • Swagger:  http://54.158.158.91:8081/swagger-ui/index.html"
echo "  • API:      http://54.158.158.91:8081/api/productos"
echo ""
echo "Comandos útiles en EC2:"
echo "  • Ver logs:    sudo journalctl -u producto-service -f"
echo "  • Estado:      sudo systemctl status producto-service"
echo "  • Reiniciar:   sudo systemctl restart producto-service"
echo "  • Verificar:   ./check-service.sh"
echo ""
echo "Deployment automático:"
echo "  • Cada push a 'main' ejecuta el deployment automáticamente"
echo "  • Monitorea en: https://github.com/ctapiad/producto-huerto/actions"
echo ""
echo "Documentación completa:"
echo "  • SETUP_COMPLETO.md - Esta guía completa"
echo "  • DEPLOYMENT.md - Detalles de deployment"
echo "  • GITHUB_SECRETS_SETUP.md - Configuración de secrets"
echo ""
echo "======================================================================"
echo "  🎉 ¡Todo listo para usar!"
echo "======================================================================"
echo ""
